name: PHP workflow

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: composer install --prefer-dist --no-progress --no-suggest



    - id: file_changes
      uses: trilom/file-changes-action@v1.2.3
    
    - name: Validate new and changed parsers 
      if: ${{ contains(join(steps.file_changes.outputs.files, ','), '.php') }}   
      run:  |
        for changed_file in ${{ steps.file_changes.outputs.files }}; do
          classScript=$( printf '$s = "%s"; $exploded = explode("/", $s); if (strpos(end($exploded), ".php") !== false) {echo preg_replace('/[^A-Za-z0-9. - _]/', '', (str_replace(".php", "", end($exploded))));} else echo "Fail" ;' $changed_file )
          class=$( php -r "$classScript");

          if [ $class != "Fail" ]; then
            echo "//////////"
            php yii parser/news "$class"
            echo "//////////"
          fi
        done
      
    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
